### ISSUE TITLE
How to check version of tsd-s3cmd installed on my machine?

### ISSUE THREAD

**Issue by ofrei** [unioslo/tsd-s3cmd#7]
I'm getting the version of the underlying ``s3cmd`` - not ``tsd-s3cmd``
```
tsd-s3cmd --version
User > p697-ofrei
Password > 
OTP > 668480
s3cmd version 2.1.0
```

**Comment by ofrei** [comment]
I've upgraded to 1.4 but still have an issue:
```
 tsd-s3cmd --version
tsd-s3cmd version unknown
- OS/Arch: Linux/x86_64
- Python: 3.7.3    
```
Also I can't reopen this github ticket...

**Comment by haatveit** [comment]
As the commit message says, this version check only works on Python 3.8 and newer because it uses `importlib.metadata.version()`, which didn't exist in the standard library earlier.

If there's an equivalent way to query the package metadata in Python 3.7 we can add that, I just didn't think it was very important since `pip show tsd-s3cmd` gives the same info.

**Comment by ofrei** [comment]
Thanks! I'll upgrade to Python 3.8. Also I didn't know about ``pip show tsd-s3cmd`` -- that's a great workaround (or not even workaround, just  the way of checking this)
